FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install axios tailwindcss postcss autoprefixer

COPY . .

COPY vite.config.js .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
