apiVersion: v1
data:
  my.cnf: |-
    [mysqld]
    innodb_buffer_pool_size=512M
    innodb_log_buffer_size=16M
    max_connections=50
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: mysql
  name: mysql-cm1
