apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
  labels:
    io.kompose.service: mysql
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  template:
    metadata:
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          args: ["--default-authentication-plugin=mysql_native_password"]
          env:
            - name: MYSQL_ROOT_PASSWORD_FILE
              value: /app/secrets/mysql-root-password
            - name: MYSQL_PASSWORD_FILE
              value: /app/secrets/db-password
            - name: MYSQL_USER
              value: user
            - name: MYSQL_DATABASE
              value: mydb
          livenessProbe:
            tcpSocket: { port: 3306 }
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: 500m
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: melk-secrets
              mountPath: /app/secrets
              readOnly: true
            - name: mysql-cm1
              mountPath: /etc/mysql/conf.d/my.cnf
              subPath: my.cnf
      volumes:
        - name: melk-secrets
          secret:
            secretName: melk-secrets
            items:
              - key: mysql-root-password
                path: mysql-root-password
              - key: db-password
                path: db-password
        - name: mysql-cm1
          configMap:
            name: mysql-cm1
            items:
              - key: my.cnf
                path: my.cnf
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
