apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: python
  name: python
spec:
  ports:
    - name: "4840"
      port: 4840
      targetPort: 4840
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: python
