#!/usr/bin/env bash
# ==========================================================
# File: lib/utils/init_lib.sh
# Purpose: Common setup helpers
# ==========================================================
# NOTE! This file must be *sourced* by init.sh – do not run it directly.
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && {
  printf "This script must be run via init.sh (source)\n" >&2
  exit 1
}

cmd_help() { 
  local cmd="$1"
  local desc="$2"
  printf "Use '%b%s%b' %s \n" "${_CYN}" "$cmd" "${_RST}" "$desc"
}

# ---------- Global defaults ----------
K8S_NS="${K8S_NS:-default}"
NON_INTERACTIVE="${NON_INTERACTIVE:-false}"

SECRETS_DIR="${SECRETS_DIR:-DIR_NAME_SECRETS}"

purge_mysql_data() {
  local data_dir="$SCRIPT_DIR/mysql/data"

  [[ -d "$data_dir" ]] || { info "No MySQL data directory to delete."; return 0; }

  if ${NON_INTERACTIVE}; then
    warn "Skipping deletion of $data_dir in non-interactive mode."
    return 0
  fi

  read -rp "Delete existing MySQL data (users/passwords)? [y/N]: " ans
  [[ $ans =~ ^[Yy]$ ]] || { info "Existing data kept."; return 0; }

  info "Stopping containers and removing volumes …"
  docker compose down -v
  info "Deleting $data_dir …"
  rm -rf "$data_dir"
  info "Data directory removed. MySQL will initialise fresh on next start-up."
}

prompt_secret() {
  local prompt="$1" file="$2" val=""

  if [[ ${use_same,,} == "y" ]]; then
    while true; do
      read -rsp "Enter password for all secrets: " val; printf "\n"
      if [[ -n "$val" ]]; then
        break
      else
        warn "Value cannot be empty. Try again."
      fi
    done
    printf '%s' "$val" > "$file" && chmod 600 "$file"
    info "Saved to $file"
    return 0
  fi

  while true; do
    ${NON_INTERACTIVE} && { err "Non-interactive mode active, but secret required ($prompt)."; return 1; }
    read -rsp "${prompt}: " val; printf "\n"
    if [[ -n "$val" ]]; then
      break
    else
      warn "Value cannot be empty. Try again."
    fi
  done
  printf '%s' "$val" > "$file" && chmod 600 "$file"
  info "Saved to $file"
}

validate_subnet() {
  local subnet="$1"
  if [[ ! "$subnet" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    err "Invalid subnet format: $subnet"
    return 1
  fi
}

create_or_edit_env_file() {
  echo
  info "Generating/updating .env …"
  local env_file="$SCRIPT_DIR/.env"; local mysql_user url_host subnet_ip

  if [[ -f "$env_file" && ${NON_INTERACTIVE} == false ]]; then
    read -rp ".env exists. Overwrite? [y/N]: " ans
    [[ $ans =~ ^[Yy]$ ]] || { warn "Cancelled by user."; return 0; }
  fi

  if ${NON_INTERACTIVE}; then
    err "--non-interactive mode requires pre-defined variables."
    return 1
  fi

  local default_mysql_user="user"
  local default_url_host="localhost"
  local default_subnet_ip="172.20.0.0"

  if [[ -z "$SERVER_NAME" || -z "$NORMAL_MYSQL_USER" || -z "$SUBNET" ]]; then
    warn "Custom environment variables are not set in init.conf, interactive mode will be used."
    echo
    important "Creating .env file for environment variables."
    info "Leave the fields empty to use defaults."
    read -rp "MySQL username (default: $default_mysql_user): " mysql_user
    read -rp "Domain/URL without https:// (default: $default_url_host): " url_host
    read -rp "Subnet Ip (default: $default_subnet_ip): " subnet_ip

    mysql_user="${mysql_user:-$default_mysql_user}"
    url_host="${url_host:-$default_url_host}"
    subnet_ip="${subnet_ip:-$default_subnet_ip}"

  else
    mysql_user="$NORMAL_MYSQL_USER"
    url_host="$SERVER_NAME"
    subnet_ip="$SUBNET"
    echo
    info "Using environment variables from init.conf."
    echo "Using MySQL user: $mysql_user"
    echo "Using domain/URL: $url_host"
    echo "Using subnet IP: $subnet_ip"
  fi

  validate_subnet "$subnet_ip" || {
    err "Invalid subnet IP: $subnet_ip"
    return 1
  }

  FRONTEND_IP="${subnet_ip%.*}.20"
  BACKEND_IP="${subnet_ip%.*}.30"
  NGINX_IP="${subnet_ip%.*}.40"
  MYSQL_IP="${subnet_ip%.*}.50"
  PYTHON_IP="${subnet_ip%.*}.60"

  cat > "$env_file" <<EOF
# Autogenerated $(date +%F)
NODE_ENV=development
VITE_API_URL=https://${url_host}/api
BASE_URL=/
VITE_WS_URL=ws://${url_host}

DB_HOST=mysql
DB_USER=${mysql_user}
DB_NAME=mydb
CORS_ORIGIN=https://${url_host}

# Self-signed cert details
NGINX_SERVER_NAME=${url_host}
NGINX_SERVER_NAME_WWW=www.${url_host}
SSL_DIR=/etc/nginx/ssl
SSL_COUNTRY_NAME=NO
SSL_STATE_OR_PROVINCE_NAME=Trondelag
SSL_LOCALITY_NAME=Trondheim
SSL_ORGANIZATION_NAME=Private

MYSQL_USER=${mysql_user}
MYSQL_DATABASE=mydb

SUBNET=${subnet_ip}/16
FRONTEND_IP=${FRONTEND_IP}
BACKEND_IP=${BACKEND_IP}
NGINX_IP=${NGINX_IP}
MYSQL_IP=${MYSQL_IP}
PYTHON_IP=${PYTHON_IP}
EOF
  chmod 600 "$env_file"
  info "Wrote $env_file"
}

create_or_edit_secrets() {
  info "Creating/updating secrets …"
  local secrets_dir="$SECRETS_DIR" ans
  if [[ -d "$secrets_dir" && ${NON_INTERACTIVE} == false ]]; then
    read -rp "Secrets directory exists. Overwrite? [y/N]: " ans
    [[ $ans =~ ^[Yy]$ ]] || { warn "Cancelled by user."; return 0; }
  fi
  mkdir -p "$secrets_dir" && chmod 700 "$secrets_dir"

  declare -A prompts=(
    [admin-password]="Password for backend user \"admin\""
    [db-password]="Password for MySQL user"
    [mysql-root-password]="Password for MySQL root"
    [session-secret]="Session secret (cookie signing)"
  )
  echo
  important "MySQL root, MySQL user, admin (web-login), og session secrets will be created."
  read -rp "Use same password for all secrets? [y/N]: " use_same
  use_same="${use_same,,}"

  if [[ "$use_same" == "y" ]]; then
    local val file key
    while true; do
      read -rsp "Enter password for all secrets: " val; printf "\n"
      if [[ -n "$val" ]]; then
        break
      else
        warn "Value cannot be empty. Try again."
      fi
    done
    for key in "${!prompts[@]}"; do
      file="$secrets_dir/$key"
      printf '%s' "$val" > "$file" && chmod 600 "$file"
      info "Saved to $file"
    done
    return 0
  fi

  for key in "${!prompts[@]}"; do
    prompt_secret "${prompts[$key]}" "$secrets_dir/$key" || return 1
  done

  info "All secrets saved."
}

# shellcheck disable=SC2153
inject_env() {
  info "Running lib/tools/inject_env.py …"
  (cd "$SCRIPT_DIR/lib/tools" && "$PYTHON_BIN" inject_env.py)
}


wait_for_mysql() {
  local cid
  cid=$(docker compose ps -q mysql) || {
    err "Failed to retrieve log for mysql container"
    return 1
  }

  local want=2 seen=0
  local timeout=60 
  local start

  start=$(date +%s) || {
    if ! docker logs "$cid" >/dev/null 2>&1; then
      err "Kunne ikke hente logg for mysql-containeren"
      return 1
    fi
  }

  echo "Waiting for MySQL (max ${timeout}s) …"

  while IFS= read -r line; do
    [[ $line == *"ready for connections"* ]] && ((seen++))
    if (( seen >= want )); then
      echo "MySQL is ready."
      break
    fi
    if (( $(date +%s) - start > timeout )); then
      echo "Timeout: MySQL is not ready."
      return 1
    fi
  done < <(docker logs -f "$cid" 2>&1)

  return 0
}


build_with_docker() {
  info "Building Docker images …"
  docker compose build
  info "Starting mysql service …"
  docker compose up mysql -d
  info "Waiting for database to be ready …"
  wait_for_mysql || return 1
  docker compose down
}

ensure_kubectl_api() {
  if kubectl version --request-timeout='10s' >/dev/null 2>&1; then
    return 0
  fi

  warn "API connection failed. Trying to start Minikube if installed ..."
  if minikube start --driver=docker >/dev/null 2>&1; then
    return 0
  fi

  err "Could not connect to Kubernetes API server. Check that Minikube/K3s is running and kubeconfig is correct."
  exit 1
}

migrate_env_to_kubectl() {
  command -v kubectl >/dev/null 2>&1 || { warn "kubectl not installed - skipping."; return 0; }
  local env_file="$SCRIPT_DIR/.env"; [[ -f "$env_file" ]] || { err ".env is missing."; return 1; }
  local out="$K8S_DIR/env-configmap.yaml"
  kubectl create configmap env --from-env-file="$env_file" --dry-run=client -o yaml > "$out" || return 1
  chmod 600 "$out"
  
  ensure_kubectl_api
  kubectl apply -f "$out" --namespace "$K8S_NS" || return 1
  info "Migrated .env to ConfigMap ($out) in namespace $K8S_NS."
}


migrate_secrets_to_kubectl() {
  command -v kubectl >/dev/null 2>&1 || { warn "kubectl not installed - skipping."; return 0; }

  [[ -d "$SECRETS_DIR" ]] || { err "Secrets directory is missing."; return 1; }
  mkdir -p "$K8S_DIR"

  local secret_name="${K8S_SECRET_NAME:-$(basename "$SECRETS_DIR")}"
  local out="$K8S_DIR/${secret_name}.yaml"

  local from_args=()
  for secret_file in "$SECRETS_DIR"/*; do
    [[ -f "$secret_file" ]] || continue
    local key
    key="$(basename "$secret_file")" || {
      if [[ -z "$key" ]]; then
        err "Secret file '$secret_file' has no valid name."
        return 1
      fi
    }
    from_args+=(--from-file="$key=$secret_file")
  done

  if [[ ${#from_args[@]} -eq 0 ]]; then
    err "No files found in $SECRETS_DIR"; return 1
  fi

  kubectl create secret generic "$secret_name" \
          "${from_args[@]}" \
          --dry-run=client -o yaml > "$out" || return 1

  chmod 600 "$out"

  ensure_kubectl_api
  kubectl apply -f "$out" --namespace "$K8S_NS" || {
    err "Apply failed for $secret_name"
    return 1
  }

  info "Secret $secret_name migrated with ${#from_args[@]} keys."

  for file in "$K8S_DIR"/*.yaml; do
    if [[ -f "$file" ]]; then
      sed -i "s/\${secrets_name}/$secret_name/g" "$file"
      info "Updated $file with secrets_name=$secret_name"
    else
      warn "No YAML files found in $K8S_DIR."
      return 0
    fi
  done
}

build_k8s_deployments() {
  info "Building Kubernetes deployment files …"
  cd "$K8S_DIR" || { err "Could not change to $K8S_DIR"; return 1; }

  for svc in "${SERVICES[@]}"; do
    [[ -f "${svc}-deployment.yaml.tpl" ]] || { err "Missing template: ${svc}-deployment.yaml.tpl"; return 1; }
  done

  [[ -n "${VERSION_APP:-}" ]] || { err "VERSION_APP is not set."; return 1; }

  case "$(uname -m)" in
    x86_64)  ARCH="amd64" ;;
    aarch64) ARCH="arm64" ;;
    *) err "Unknown architecture: $(uname -m)"; exit 1 ;;
  esac
  info "Detected architecture: $ARCH"
  export VERSION_APP ARCH

  for svc in "${SERVICES[@]}"; do
    envsubst '$VERSION_APP $ARCH' < "${svc}-deployment.yaml.tpl" > "${svc}-deployment.yaml"
    info "Built ${svc}-deployment.yaml for $ARCH"
  done
  cd - >/dev/null 2>&1 || return 1
  info "Finished building deployment files."

  local ingress_file="$K8S_DIR/ingress-nginx.yaml"
  if [[ -f "$ingress_file" ]]; then
    if [[ -f "$SCRIPT_DIR/.env" ]]; then
      # shellcheck source=/dev/null
      source "$SCRIPT_DIR/.env"
      if [[ -n "${NGINX_SERVER_NAME:-}" ]]; then
        sed -i "s/\${DOMAIN_NAME}/$NGINX_SERVER_NAME/g" "$ingress_file"
        info "Updated $ingress_file with DOMAIN_NAME=$NGINX_SERVER_NAME"
      else
        warn "DOMAIN_NAME is not set in .env"
      fi
    fi
  fi
}

init_docker_compose() {
  info "Creating docker-compose.yaml from template …"
  local template="$SCRIPT_DIR/docker-compose.template.yaml"
  [[ -f "$template" ]] || { err "Template $template not found."; return 1; }

  local out="$SCRIPT_DIR/docker-compose.yaml"

  #check if the .env file does not exist
  if [[ ! -f "$SCRIPT_DIR/.env" ]]; then
    err ".env file is missing. Please create it first."
    return 1
  fi
  # shellcheck source=/dev/null
  source "$SCRIPT_DIR/.env"

  if [[ -z "${SUBNET:-}" ]]; then
    err "SUBNET variable is not set in .env file."
    return 1
  fi

  export SUBNET NGINX_IP FRONTEND_IP BACKEND_IP MYSQL_IP PYTHON_IP
  envsubst < "$template" > "$out" || { err "Failed to create $out"; return 1; }
}

replace_k8s_namespace() {
  local namespace="${K8S_NS:-default}"
  info "Replacing namespace in Kubernetes YAML files with '$namespace' ..."
  for file in "$K8S_DIR"/*.yaml; do
    if [[ -f "$file" ]]; then
      sed -i "s/namespace: .*/namespace: $namespace/" "$file"
      info "Updated namespace in $file"
    else
      warn "No YAML files found in $K8S_DIR."
      return 0
    fi
  done
  info "Namespace replacement complete."
}

create_namespace_if_not_exists() {
  command -v kubectl >/dev/null 2>&1 || { warn "kubectl not installed - skipping namespace creation."; return 0; }
  if ! kubectl get namespace "$K8S_NS" >/dev/null 2>&1; then
    info "Creating Kubernetes namespace '$K8S_NS' ..."
    kubectl create namespace "$K8S_NS" || { err "Failed to create namespace $K8S_NS"; return 1; }
  else
    info "Namespace '$K8S_NS' already exists."
  fi
}

run_tunnel() {
  local pidfile="$HOME/minikube-tunnel.pid"
  local logfile="$HOME/minikube-tunnel.log"

  if [[ -f "$pidfile" ]]; then
    local pid
    pid="$(cat "$pidfile" 2>/dev/null || true)"
    if [[ -n "$pid" ]] && sudo kill -0 "$pid" 2>/dev/null; then
      if sudo ps -o args= -p "$pid" 2>/dev/null | grep -q "minikube tunnel"; then
        return 0
      fi
    fi
  fi

  sudo bash -c "nohup minikube tunnel >> '$logfile' 2>&1 & echo \$! > '$pidfile'"

  sleep 0.3
  local pid
  pid="$(cat "$pidfile" 2>/dev/null || true)"
  if [[ -z "$pid" ]] || ! sudo kill -0 "$pid" 2>/dev/null; then
    return 1
  fi
}

cleanup_minikube_tunnel() {
  local pidfile="$HOME/minikube-tunnel.pid"
  local logfile="$HOME/minikube-tunnel.log"
  local killed_by_pid=0

  if [[ -f "$pidfile" ]]; then
    local pid
    pid="$(cat "$pidfile" 2>/dev/null || true)"
    if [[ -n "$pid" ]] && sudo kill -0 "$pid" 2>/dev/null; then
      if sudo ps -o args= -p "$pid" 2>/dev/null | grep -q "minikube tunnel"; then
        sudo kill "$pid" 2>/dev/null || true

        for _ in {1..20}; do
          sleep 0.1
          sudo kill -0 "$pid" 2>/dev/null || { killed_by_pid=1; break; }
        done

        if [[ $killed_by_pid -eq 0 ]] && sudo kill -0 "$pid" 2>/dev/null; then
          sudo kill -9 "$pid" 2>/dev/null || true
          killed_by_pid=1
        fi
      fi
    fi

    rm -f "$pidfile" 2>/dev/null || sudo rm -f "$pidfile" 2>/dev/null || true
    rm -f "$logfile" 2>/dev/null || true
  fi

  sudo pkill -f "[m]inikube(.+)?tunnel" 2>/dev/null || true

  sudo rm -f ~/.minikube/tunnel.lock /var/lib/minikube/tunnel.lock 2>/dev/null || true
  sudo chown -R "$USER:$USER" ~/.minikube ~/.kube 2>/dev/null || true
}



setup_minikube_tunnel() {
  command -v minikube >/dev/null 2>&1 || { warn "Minikube not installed - skipping tunnel setup."; return 0; }
    ensure_kubectl_api
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/baremetal/deploy.yaml

    kubectl -n ingress-nginx patch svc ingress-nginx-controller \
      -p '{"spec":{"type":"LoadBalancer"}}'
    kubectl rollout status deployment ingress-nginx-controller \
      -n ingress-nginx --timeout=120s || return 1

    run_tunnel

    kubectl apply -f "$K8S_DIR/" \
      --selector='app.kubernetes.io/name!=ingress-nginx' || return 1

    cleanup_minikube_tunnel || {
      err "Failed to clean up Minikube tunnel."
      return 1
    }

    kubectl apply -f "$K8S_DIR/" >/dev/null || {
      err "Failed to apply Kubernetes configurations."
      return 1
    }
}

cleanup_kube() {
  info "Cleaning up Kubernetes resources ..."
  kubectl delete -f "$K8S_DIR/" >/dev/null 2>&1 || true

  if command -v minikube >/dev/null 2>&1; then
    info "Stopping Minikube ..."
    minikube stop >/dev/null 2>&1 || true
  fi
  return 0
}

init_amd64() {
  if command -v minikube >/dev/null 2>&1; then
    info "Minikube is already installed."
  else
    if ${NON_INTERACTIVE}; then
      err "Non-interactive mode active, but Minikube is not installed."
      return 1
    fi
    read -rp "Minikube is not installed. Do you want to install it? [y/N]: " ans
    if [[ $ans =~ ^[Yy]$ ]]; then
      info "Installing Minikube ..."
      curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
      sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
      info "Minikube installed successfully."

      # Start Minikube with Docker driver
      if ! minikube start --driver=docker; then
        err "Failed to start Minikube. Ensure Docker is running."
        return 1
      fi
    else
      warn "Skipping Minikube installation."
    fi
  fi

  
  local ingress_file="$K8S_DIR/ingress-nginx.yaml.tpl"
  local ingress_out="$K8S_DIR/ingress-nginx.yaml"

  if [[ -f "$ingress_file" && -f "$SCRIPT_DIR/.env" ]]; then
    # shellcheck source=/dev/null
    source "$SCRIPT_DIR/.env"
    if [[ -n "${NGINX_SERVER_NAME:-}" ]]; then
      sed "s/\${NGINX_SERVER_NAME}/$NGINX_SERVER_NAME/g" "$ingress_file" > "$ingress_out"
    fi
  fi
  info "Ingress configuration written to $ingress_out"

  setup_minikube_tunnel || return 1
  cleanup_kube
}

setup_traefik() {
  info "Setting up Traefik ingress controller ..."

  : "${K8S_DIR:?K8S_DIR is unset}"
  : "${SCRIPT_DIR:?SCRIPT_DIR is unset}"
  : "${K8S_NS:?K8S_NS is unset}"

  local ingress_file="$K8S_DIR/ingress-traefik.yaml.tpl"
  local ingress_out="$K8S_DIR/ingress-traefik.yaml"

  [[ -f "$ingress_file" ]] || { err "Missing template: $ingress_file"; return 1; }
  [[ -f "$SCRIPT_DIR/.env" ]] || { err "Missing .env: $SCRIPT_DIR/.env"; return 1; }

  set -a
  # shellcheck disable=SC1091
  source "$SCRIPT_DIR/.env"
  set +a

  [[ -n "${NGINX_SERVER_NAME:-}" ]] || { err "NGINX_SERVER_NAME not set in .env"; return 1; }

  if ! grep -q '\${NGINX_SERVER_NAME}' "$ingress_file"; then
    warn "Placeholder \${NGINX_SERVER_NAME} not found in $ingress_file"
  fi

  if ! envsubst '${NGINX_SERVER_NAME}' < "$ingress_file" > "$ingress_out"; then
    err "envsubst failed"
    return 1
  fi

  [[ -s "$ingress_out" ]] || { err "Output file is empty: $ingress_out"; return 1; }
  info "Ingress configuration written to $ingress_out"
  
  ensure_kubectl_api
  kubectl apply -n "$K8S_NS" -f "$ingress_out" || {
    err "Failed to apply Traefik ingress configuration."
    return 1
  }
}

init_arm64() {
  
  if command -v k3s >/dev/null 2>&1; then
    info "K3s is already installed."
  else
    if ${NON_INTERACTIVE}; then
      err "Non-interactive mode active, but K3s is not installed."
      return 1
    fi
    read -rp "K3s is not installed. Do you want to install it? [y/N]: " ans
    if [[ $ans =~ ^[Yy]$ ]]; then
      info "Installing K3s ..."
      curl -sfL https://get.k3s.io | sh -

      mkdir -p ~/.kube
      
      uid=$(id -u)
      gid=$(id -g)
      sudo chown "${uid}:${gid}" ~/.kube/config

      export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

      info "K3s installed successfully."

    else
      warn "Skipping K3s installation."
    fi
  fi

  setup_traefik || return 1
}

handle_architecture() {
  local arch
  arch=$(uname -m)

  case "$arch" in
    x86_64)
      info "Initializing for AMD64 architecture..."
      init_amd64 || return 1
      ;;
    aarch64 | arm64)
      info "Initializing for ARM64 architecture..."
      init_arm64 || return 1
      ;;
    *)
      err "Unsupported architecture: $arch, no compatible installation method available."
      return 1
      ;;
  esac
  return 0
}


core_setup() {
  purge_mysql_data           || return 1
  create_or_edit_secrets     || return 1
  create_or_edit_env_file    || return 1
  init_docker_compose        || return 1
  inject_env                 || return 1
  build_with_docker          || return 1
}

display_kubernetes_instructions() {
  echo
  info "Run the following 3 commands in order to successfully start the Minikube cluster:"
  cmd_help "minikube start" "to start the Minikube cluster."
  cmd_help "minikube tunnel" "in a separate terminal to expose services."
  cmd_help "kubectl apply -f k8s/" "to deploy your services."
  info "After starting the Minikube cluster, you can use the following commands:"
  cmd_help "kubectl get pods -n $K8S_NS" "to check pod status."
  cmd_help "kubectl describe pod <pod-name> -n $K8S_NS" "for detailed info."
  cmd_help "kubectl logs <pod-name> -n $K8S_NS" "to view logs."
  cmd_help "kubectl exec -it <pod-name> -n $K8S_NS -- /bin/bash" "to access a pod shell."
  cmd_help "kubectl delete -f k8s/" "to clean up all resources."
  echo "For more help, refer to the Kubernetes documentation."
}

print_permission_reminder() {
  echo
  important "Remember to set up Docker permissions correctly:"
  cmd_help "sudo usermod -aG docker $USER" "to add your user to the docker group."
  cmd_help "newgrp docker" "to apply the group changes without logging out."
  echo
}

print_admin_username() {
  source "$SCRIPT_DIR/.env"

  local url
  if [[ -n "${NGINX_SERVER_NAME:-}" ]]; then
    url="http://${NGINX_SERVER_NAME}"
  else
    url="http://localhost"
  fi

  echo
  info "Website is located at: $url"
  important "To log in to the website, username is 'admin', and the password is the one you set during installation."

}

init_with_both() {
  core_setup                 || return 1
  build_k8s_deployments      || return 1
  migrate_env_to_kubectl     || return 1
  migrate_secrets_to_kubectl || return 1
  replace_k8s_namespace      || return 1
  create_namespace_if_not_exists || return 1
  handle_architecture        || return 1

  info "Kubernetes and docker compose setup complete."
  display_kubernetes_instructions
  info "You can also run the application locally. Make sure minikube is not running."
  cmd_help "minikube stop" "to stop the Minikube cluster."
  cmd_help "docker compose up -d" "to run the application locally."
  cmd_help "docker compose down" "to stop the application."
  print_permission_reminder
  exit 0

}

init_with_kubectl() {
  if ! command -v kubectl >/dev/null 2>&1; then
    err "kubectl is not installed. Please install it first."
    return 1
  fi

  create_or_edit_secrets     || return 1
  create_or_edit_env_file    || return 1

  source "$SCRIPT_DIR/.env" || {
    err "Failed to source .env file."
    return 1
  }

  build_k8s_deployments      || return 1
  migrate_env_to_kubectl     || return 1
  migrate_secrets_to_kubectl || return 1
  replace_k8s_namespace      || return 1
  create_namespace_if_not_exists || return 1
  handle_architecture        || return 1

  print_permission_reminder
  info "Kubernetes and docker compose setup complete."
  display_kubernetes_instructions
  
  exit 0

}

init_with_docker() {
  core_setup || return 1

  print_permission_reminder
  info "Docker setup complete."
  echo
  cmd_help "docker compose up -d" "to run the application locally."
  cmd_help "docker compose down" "to stop the application."
  
  exit 0
}